# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys
import time
import easygui
import serial

from PyQt5.QtCore import QThread, pyqtSignal
from PyQt5.QtWidgets import QApplication, QMessageBox, QMainWindow
from PyQt5.uic import loadUi
from SerialPortFunc import detectPort, openPort, selectPort, closePort
from ReadJSON import *
import tkinter as tk
from tkinter import filedialog
from MsgBox import showdialog
from LocalFileRead import openFile
#FILE_LIMIT = 100
#RATE_OF_CHANGE = 1

global ser_1

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

from ReadJSON import getFolderURL, getPortNo, getBrate,getDataBits, getParity, getStopBits
from SerialPortFunc import detectPort


class Ui_DNCLoggerMainScreen(object):
    def setupUi(self, DNCLoggerMainScreen):
        DNCLoggerMainScreen.setObjectName("DNCLoggerMainScreen")
        DNCLoggerMainScreen.setWindowModality(QtCore.Qt.WindowModal)
        DNCLoggerMainScreen.resize(539, 305)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DNCLoggerMainScreen.sizePolicy().hasHeightForWidth())
        DNCLoggerMainScreen.setSizePolicy(sizePolicy)
        DNCLoggerMainScreen.setTabletTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../GUIPractice/n-c-tools-120x120.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DNCLoggerMainScreen.setWindowIcon(icon)
        DNCLoggerMainScreen.setInputMethodHints(QtCore.Qt.ImhNoEditMenu)
        DNCLoggerMainScreen.setTabShape(QtWidgets.QTabWidget.Triangular)
        DNCLoggerMainScreen.setDockNestingEnabled(False)
        DNCLoggerMainScreen.setProperty("flag", "")
        self.centralwidget = QtWidgets.QWidget(DNCLoggerMainScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 190, 521, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.progress = QtWidgets.QProgressBar(self.centralwidget)
        self.progress.setGeometry(QtCore.QRect(10, 203, 481, 23))
        self.progress.setProperty("value", 24)
        self.progress.setObjectName("progress")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(10, 220, 521, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 233, 521, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout.setSpacing(17)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sendBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sendBtn.sizePolicy().hasHeightForWidth())
        self.sendBtn.setSizePolicy(sizePolicy)
        self.sendBtn.setObjectName("sendBtn")
        self.horizontalLayout.addWidget(self.sendBtn)
        self.pauseBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pauseBtn.sizePolicy().hasHeightForWidth())
        self.pauseBtn.setSizePolicy(sizePolicy)
        self.pauseBtn.setObjectName("pauseBtn")
        self.horizontalLayout.addWidget(self.pauseBtn)
        self.resumeBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resumeBtn.sizePolicy().hasHeightForWidth())
        self.resumeBtn.setSizePolicy(sizePolicy)
        self.resumeBtn.setObjectName("resumeBtn")
        self.horizontalLayout.addWidget(self.resumeBtn)
        self.abortBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.abortBtn.sizePolicy().hasHeightForWidth())
        self.abortBtn.setSizePolicy(sizePolicy)
        self.abortBtn.setObjectName("abortBtn")
        self.horizontalLayout.addWidget(self.abortBtn)
        self.restartBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.restartBtn.sizePolicy().hasHeightForWidth())
        self.restartBtn.setSizePolicy(sizePolicy)
        self.restartBtn.setObjectName("restartBtn")
        self.horizontalLayout.addWidget(self.restartBtn)
        self.backBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backBtn.sizePolicy().hasHeightForWidth())
        self.backBtn.setSizePolicy(sizePolicy)
        self.backBtn.setObjectName("backBtn")
        self.horizontalLayout.addWidget(self.backBtn)
        self.horizontalLayout.setStretch(0, 5)
        self.horizontalLayout.setStretch(1, 5)
        self.horizontalLayout.setStretch(2, 5)
        self.horizontalLayout.setStretch(3, 5)
        self.horizontalLayout.setStretch(4, 5)
        self.horizontalLayout.setStretch(5, 5)
        self.fileDisplay = QtWidgets.QListWidget(self.centralwidget)
        self.fileDisplay.setGeometry(QtCore.QRect(4, 0, 341, 191))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileDisplay.sizePolicy().hasHeightForWidth())
        self.fileDisplay.setSizePolicy(sizePolicy)
        self.fileDisplay.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.fileDisplay.setModelColumn(0)
        self.fileDisplay.setObjectName("fileDisplay")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(349, 0, 181, 191))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setRowWrapPolicy(QtWidgets.QFormLayout.WrapLongRows)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.labelPortNo = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelPortNo.setObjectName("labelPortNo")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelPortNo)
        self.labelBuadRate = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelBuadRate.setObjectName("labelBuadRate")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelBuadRate)
        self.labelParity = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelParity.setObjectName("labelParity")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelParity)
        self.labelDataBits = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelDataBits.setObjectName("labelDataBits")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.labelDataBits)
        self.labelStopBits = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelStopBits.setObjectName("labelStopBits")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.labelStopBits)
        self.labelCurFile = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelCurFile.setObjectName("labelCurFile")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.labelCurFile)
        self.labelPortNo_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelPortNo_2.setObjectName("labelPortNo_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.labelPortNo_2)
        self.labelBuadRate_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelBuadRate_2.setObjectName("labelBuadRate_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.labelBuadRate_2)
        self.labelParity_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelParity_2.setObjectName("labelParity_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.labelParity_2)
        self.labelDataBits_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelDataBits_2.setObjectName("labelDataBits_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.labelDataBits_2)
        self.labelStopBits_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelStopBits_2.setObjectName("labelStopBits_2")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.labelStopBits_2)
        self.labelCurFile_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelCurFile_2.setObjectName("labelCurFile_2")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.labelCurFile_2)
        DNCLoggerMainScreen.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(DNCLoggerMainScreen)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 539, 21))
        self.menubar.setObjectName("menubar")
        DNCLoggerMainScreen.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(DNCLoggerMainScreen)
        self.statusbar.setObjectName("statusbar")
        DNCLoggerMainScreen.setStatusBar(self.statusbar)

        self.retranslateUi(DNCLoggerMainScreen)
        QtCore.QMetaObject.connectSlotsByName(DNCLoggerMainScreen)


#------------------------------Logic Starts Here-------------------------------
        self.sendBtn.clicked.connect(self.on_sendBtn1_clicked)
        self.pauseBtn.clicked.connect(self.on_pauseBtn1_clicked)
        self.resumeBtn.clicked.connect(self.on_resumeBtn1_clicked)
        self.abortBtn.clicked.connect(self.on_abortBtn1_clicked)
        self.restartBtn.clicked.connect(self.on_restartBtn1_clicked)
        self.backBtn.clicked.connect(self.on_backBtn1_clicked)

        list_of_ports = detectPort()
        print(list_of_ports)

    def displayFile(self):
        file_path_string = easygui.fileopenbox(msg="Select single file at a time.", title="Choose",
                                               default=getFolderURL(),
                                               filetypes=None, multiple=False)
        file_path_string = (file_path_string.replace('\\', "/"))
        x = file_path_string.split("/")
        l = len(x)

        file_path = getFolderURL() + x[l - 1]
        print(file_path)
        print(getPortNo(), getBrate(), getDataBits(), getParity(), getStopBits())
        detectPort()
        ser_1 = openPort(getPortNo(), getBrate(), getDataBits(), getParity(), getStopBits())

        fileptr = open(file_path, "r")
        # self.countLines(file_path)
        lineno = 0;

        while True:
            line = fileptr.readline()
            QMessageBox.information(self, "Info", line)
            lineno += 1
            if not line:
                break

            # selectPort()
            #              self.split_to_char(line)
            ser_1.write(line.encode())

            # write code to send char over COM port here

            #  closePort(ser_1)

            fullline = "{}".format(lineno) + "  " + line.strip()
            self.addLineToFileDisplay(fullline)

        # showdialog()
        fileptr.close()
        closePort(ser_1)
        # except(Exception):

        #   print("Display file error")

    def split_to_char(self, word):
        #     print(word)
        #        print (len(word))
        for x in range(len(word)):
            ch1 = word[x]
            ser_1.write(ch1.encode())
            print(ch1)
        # return (word)



    def on_sendBtn1_clicked(self):
        print("Send Btn Clicked")
        file_path_string = ""
        try:
            self.displayFile()
        except(IOError,Exception):
            print(Exception)

    def on_pauseBtn1_clicked(self):
        print("Pause Btn Clicked")

    def on_resumeBtn1_clicked(self):
        print("Resume Btn Clicked")

    def on_abortBtn1_clicked(self):
        print("Abort Btn Clicked")

    def on_restartBtn1_clicked(self):
        print("Restart Btn Clicked")

    def on_backBtn1_clicked(self):
        print("back Btn Clicked")

    def addLineToFileDisplay(self,line):
        self.fileDisplay.addItem(line)

# ------------------------------Logic Ends Here-------------------------------

    def retranslateUi(self, DNCLoggerMainScreen):
        _translate = QtCore.QCoreApplication.translate
        DNCLoggerMainScreen.setWindowTitle(_translate("DNCLoggerMainScreen", "Nectar DNC Logger"))
        self.sendBtn.setText(_translate("DNCLoggerMainScreen", "Send"))
        self.pauseBtn.setText(_translate("DNCLoggerMainScreen", "Pause"))
        self.resumeBtn.setText(_translate("DNCLoggerMainScreen", "Resume"))
        self.abortBtn.setText(_translate("DNCLoggerMainScreen", "Abort"))
        self.restartBtn.setText(_translate("DNCLoggerMainScreen", "Restart"))
        self.backBtn.setText(_translate("DNCLoggerMainScreen", "Back"))
        self.labelPortNo.setText(_translate("DNCLoggerMainScreen", "Port:"))
        self.labelBuadRate.setText(_translate("DNCLoggerMainScreen", "Baud Rate:"))
        self.labelParity.setText(_translate("DNCLoggerMainScreen", "Parity:"))
        self.labelDataBits.setText(_translate("DNCLoggerMainScreen", "Data Bits:"))
        self.labelStopBits.setText(_translate("DNCLoggerMainScreen", "Stop Bits:"))
        self.labelCurFile.setText(_translate("DNCLoggerMainScreen", "Current File:"))
        self.labelPortNo_2.setText(_translate("DNCLoggerMainScreen", "NA"))
        self.labelBuadRate_2.setText(_translate("DNCLoggerMainScreen", "NA"))
        self.labelParity_2.setText(_translate("DNCLoggerMainScreen", "NA"))
        self.labelDataBits_2.setText(_translate("DNCLoggerMainScreen", "NA"))
        self.labelStopBits_2.setText(_translate("DNCLoggerMainScreen", "NA"))
        self.labelCurFile_2.setText(_translate("DNCLoggerMainScreen", "NA"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DNCLoggerMainScreen = QtWidgets.QMainWindow()
    ui = Ui_DNCLoggerMainScreen()
    ui.setupUi(DNCLoggerMainScreen)
    DNCLoggerMainScreen.show()
    sys.exit(app.exec_())
